// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owzkyqwtnzximkrrqcoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93emt5cXd0bnp4aW1rcnJxY29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MTUzNTMsImV4cCI6MjA3MzI5MTM1M30.19fzF70rZE3tdfXuATEpxpBvoIq8OGIjaekXP5_JITE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});